name: CMake C++ CUDA CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: CUDA Toolkit installieren
      uses: Jimver/cuda-toolkit@v0.2.15
      with:
        cuda: '13.0.0'

    - name: Create Build Directory
      run: cmake -B build -S .

    - name: Compile Project
      run: cmake --build build --config Release

    - name: Run Tests (optional)
      run: ctest --test-dir build --output-on-failure
